# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0003_auto_20170515_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node_dir',
            options={'ordering': ('-date_updated',)},
        ),
    ]
