# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0004_auto_20170516_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_dir',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
