# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0005_auto_20170517_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node_dir',
            options={},
        ),
        migrations.RemoveField(
            model_name='node_dir',
            name='date_updated',
        ),
    ]
