# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0006_auto_20170517_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node_dir',
            options={'ordering': ('-date_updated',)},
        ),
        migrations.AddField(
            model_name='node_dir',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
