# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0007_auto_20170517_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node_dir',
            options={'ordering': ('name',)},
        ),
    ]
