# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0009_node_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='analysis',
            field=models.BooleanField(default=False),
        ),
    ]
