# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0011_breaking_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking_link',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='breaking_link',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
