# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0012_auto_20170627_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_node_related_+', to='nodanews.Node'),
        ),
    ]
