# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0018_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='bio',
            field=models.TextField(default='bio goes here'),
        ),
    ]
