# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0019_journalist_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video1', models.CharField(blank=True, default='', max_length=500)),
                ('video2', models.CharField(blank=True, default='', max_length=500)),
                ('video3', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
