# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0021_journalist_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_dir',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_node_dir_related_+', to='nodanews.Node_Dir'),
        ),
    ]
