# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0022_node_dir_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='hotness',
            field=models.BooleanField(default=False),
        ),
    ]
