# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0024_auto_20171002_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendlink',
            name='media',
        ),
        migrations.RemoveField(
            model_name='trendlink',
            name='perspective',
        ),
        migrations.RemoveField(
            model_name='trendperspective',
            name='trend',
        ),
        migrations.DeleteModel(
            name='Trend',
        ),
        migrations.DeleteModel(
            name='TrendLink',
        ),
        migrations.DeleteModel(
            name='TrendPerspective',
        ),
    ]
