# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0025_auto_20171002_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('picture', models.ImageField(default=' ', upload_to='media/logos')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Media_Org')),
            ],
        ),
        migrations.CreateModel(
            name='TrendPerspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=47)),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Trend')),
            ],
        ),
        migrations.AddField(
            model_name='trendlink',
            name='perspective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.TrendPerspective'),
        ),
    ]
