# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0026_auto_20171002_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendlink',
            name='media',
        ),
        migrations.RemoveField(
            model_name='trendlink',
            name='perspective',
        ),
        migrations.AddField(
            model_name='trendperspective',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Media_Org'),
        ),
        migrations.AddField(
            model_name='trendperspective',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='trendperspective',
            name='url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='TrendLink',
        ),
    ]
