# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0027_auto_20171002_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendperspective',
            name='url',
        ),
    ]
