# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0028_remove_trendperspective_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendperspective',
            name='url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
