# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0029_trendperspective_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Media_Org')),
            ],
        ),
        migrations.RemoveField(
            model_name='trendperspective',
            name='media',
        ),
        migrations.RemoveField(
            model_name='trendperspective',
            name='title',
        ),
        migrations.RemoveField(
            model_name='trendperspective',
            name='url',
        ),
        migrations.AddField(
            model_name='trend',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='trend',
            name='video1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='trend',
            name='video2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='trendperspective',
            name='choices',
            field=models.CharField(blank=True, default='0=white, 1=blue, 2=red, 3=green, 4=purple, 5=orange, 6=pink, 7=cyan', max_length=500),
        ),
        migrations.AddField(
            model_name='trendperspective',
            name='color',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trend',
            name='picture',
            field=models.ImageField(default=' ', upload_to='media/nodes'),
        ),
        migrations.AddField(
            model_name='trendlink',
            name='perspective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.TrendPerspective'),
        ),
    ]
