# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0030_auto_20171003_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trend',
            options={'ordering': ('date_updated',)},
        ),
    ]
