# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0031_auto_20171003_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendperspective',
            options={'ordering': ('-id',)},
        ),
    ]
