# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-08 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0033_node_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='content',
        ),
    ]
