# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 01:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0034_remove_node_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breaking_link',
            options={'ordering': ('-posted',)},
        ),
        migrations.AddField(
            model_name='breaking_link',
            name='posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
