# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-19 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0035_auto_20171014_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='trend',
            name='video1',
        ),
        migrations.RemoveField(
            model_name='trend',
            name='video2',
        ),
        migrations.AddField(
            model_name='trendvideo',
            name='trend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Trend'),
        ),
    ]
