# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0036_auto_20171019_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaking_link',
            name='region',
            field=models.ForeignKey(default=8, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Region'),
        ),
        migrations.AddField(
            model_name='livevideo',
            name='region',
            field=models.ForeignKey(default=8, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Region'),
        ),
    ]
