# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0037_auto_20171101_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendlink',
            name='media',
        ),
        migrations.RemoveField(
            model_name='trendlink',
            name='perspective',
        ),
        migrations.RemoveField(
            model_name='trendperspective',
            name='trend',
        ),
        migrations.RemoveField(
            model_name='trendvideo',
            name='trend',
        ),
        migrations.DeleteModel(
            name='Trend',
        ),
        migrations.DeleteModel(
            name='TrendLink',
        ),
        migrations.DeleteModel(
            name='TrendPerspective',
        ),
        migrations.DeleteModel(
            name='TrendVideo',
        ),
    ]
