# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0038_auto_20171101_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevideo',
            name='live1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livevideo',
            name='live2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livevideo',
            name='live3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livevideo',
            name='name1',
            field=models.CharField(default='name goes here', max_length=200),
        ),
        migrations.AddField(
            model_name='livevideo',
            name='name2',
            field=models.CharField(default='name goes here', max_length=200),
        ),
        migrations.AddField(
            model_name='livevideo',
            name='name3',
            field=models.CharField(default='name goes here', max_length=200),
        ),
    ]
