# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0039_auto_20171102_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breaking_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=350)),
            ],
        ),
    ]
