# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-10 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0040_breaking_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaking_link',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Breaking_Category'),
        ),
    ]
