# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-14 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0041_breaking_link_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Breaking_Category'),
        ),
    ]
