# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-14 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0042_node_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breaking_category',
            options={'ordering': ('name',)},
        ),
    ]
