# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0044_node_dir_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breaking_link',
            name='category',
        ),
        migrations.RemoveField(
            model_name='node',
            name='category',
        ),
        migrations.RemoveField(
            model_name='node_dir',
            name='category',
        ),
        migrations.DeleteModel(
            name='Breaking_Category',
        ),
    ]
