# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0045_auto_20180131_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livevideo',
            name='live1',
        ),
        migrations.RemoveField(
            model_name='livevideo',
            name='live2',
        ),
        migrations.RemoveField(
            model_name='livevideo',
            name='live3',
        ),
        migrations.RemoveField(
            model_name='media_org',
            name='fake_or_not',
        ),
        migrations.RemoveField(
            model_name='node',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='node',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='node',
            name='hotness',
        ),
        migrations.AddField(
            model_name='livevideo',
            name='name4',
            field=models.CharField(default='name goes here', max_length=200),
        ),
        migrations.AddField(
            model_name='livevideo',
            name='video4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
