# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0047_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='image',
            field=models.ImageField(default='', upload_to='media/nodes'),
        ),
    ]
