# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-05 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0048_headline_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalBiasNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=300)),
                ('title', models.CharField(default='', max_length=150)),
                ('posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Media_Org')),
                ('region', models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Region')),
            ],
            options={
                'ordering': ('-posted',),
            },
        ),
    ]
