# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0050_auto_20180205_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='text',
        ),
        migrations.RemoveField(
            model_name='livevideo',
            name='region',
        ),
        migrations.RemoveField(
            model_name='livevideo',
            name='video4',
        ),
        migrations.AddField(
            model_name='headline',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='breaking_link',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/temp'),
        ),
        migrations.AlterField(
            model_name='headline',
            name='image',
            field=models.ImageField(default='', upload_to='media/temp'),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
