# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0051_auto_20180214_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
