# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0052_auto_20180214_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livevideo',
            name='name4',
        ),
        migrations.AddField(
            model_name='livevideo',
            name='region',
            field=models.ForeignKey(default=8, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Region'),
        ),
    ]
