# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-01 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0053_auto_20180214_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_org',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
    ]
