# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-01 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0054_media_org_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='slug',
            field=models.SlugField(default=' ', max_length=200),
        ),
    ]
