# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0055_node_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Media_Org')),
            ],
        ),
        migrations.CreateModel(
            name='AnalPerspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=47)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='', max_length=200)),
                ('date_posted', models.DateField()),
                ('head_image', models.ImageField(default='', upload_to='media/nodes')),
                ('summary', models.TextField()),
                ('text1', models.TextField()),
                ('second_image', models.ImageField(default='', upload_to='media/nodes')),
                ('text2', models.TextField()),
                ('pop_out_quote', models.TextField()),
                ('video_embed1', models.CharField(blank=True, default='', max_length=500)),
                ('video_embed2', models.CharField(blank=True, default='', max_length=500)),
                ('video_embed3', models.CharField(blank=True, default='', max_length=500)),
                ('node_direc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Node_Dir')),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='', max_length=200)),
                ('date_posted', models.DateField()),
                ('head_image', models.ImageField(default='', upload_to='media/nodes')),
                ('text', models.TextField()),
                ('slug', models.SlugField(default=' ', max_length=200)),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
        migrations.AddField(
            model_name='analperspective',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Analysis'),
        ),
        migrations.AddField(
            model_name='anallink',
            name='perspective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.AnalPerspective'),
        ),
    ]
