# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-03 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0057_remove_node_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='slug',
            field=models.SlugField(default=' ', max_length=200),
        ),
    ]
