# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0058_analysis_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='banner',
            field=models.BooleanField(default=False),
        ),
    ]
