# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-10 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0060_auto_20180406_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaking_link',
            name='journalist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Journalist'),
        ),
    ]
