# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-10 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0061_breaking_link_journalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
    ]
