# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0062_journalist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='anallink',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Journalist'),
        ),
    ]
