# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0063_anallink_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='anallink',
            name='academic',
            field=models.BooleanField(default=False),
        ),
    ]
