# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0064_anallink_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anallink',
            name='media',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Media_Org'),
        ),
    ]
