# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0066_auto_20180412_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaking_link',
            name='oped',
            field=models.BooleanField(default=False),
        ),
    ]
