# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0067_breaking_link_oped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breaking_link',
            name='oped',
        ),
    ]
