# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-16 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0068_remove_breaking_link_oped'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
