# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0071_politicalissue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalissue',
            name='head_image',
            field=models.ImageField(default='', upload_to='media/nodes'),
        ),
        migrations.AddField(
            model_name='politicalissue',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
        ),
    ]
