# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-16 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0072_auto_20180416_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalbiasnews',
            name='conservative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicalbiasnews',
            name='liberal',
            field=models.BooleanField(default=True),
        ),
    ]
