# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-11 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0073_auto_20180416_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politicalissue',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='node',
            name='slug',
            field=models.SlugField(default=' ', max_length=200),
        ),
    ]
