# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0074_auto_20180611_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='credit1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='credit2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='lead',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='node',
            name='my_take2',
            field=models.TextField(default=''),
        ),
    ]
