# Generated by Django 2.1.1 on 2018-09-13 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0075_auto_20180711_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='livevideo',
            name='region',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='node_dir',
            name='related',
        ),
        migrations.AlterField(
            model_name='breaking_link',
            name='journalist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodanews.Journalist'),
        ),
        migrations.AlterField(
            model_name='breaking_link',
            name='region',
            field=models.ForeignKey(default=8, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodanews.Region'),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodanews.Media_Org'),
        ),
        migrations.AlterField(
            model_name='media_org',
            name='media_character',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodanews.Media_Character'),
        ),
        migrations.AlterField(
            model_name='media_org',
            name='political_lean',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodanews.Political_Lean'),
        ),
        migrations.AlterField(
            model_name='media_org',
            name='region',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodanews.Region'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_direc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodanews.Node_Dir'),
        ),
        migrations.AlterField(
            model_name='node',
            name='region',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodanews.Region'),
        ),
        migrations.DeleteModel(
            name='LiveVideo',
        ),
        migrations.AddField(
            model_name='topic_link',
            name='journalist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodanews.Journalist'),
        ),
        migrations.AddField(
            model_name='topic_link',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Media_Org'),
        ),
        migrations.AddField(
            model_name='topic_link',
            name='node_dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Node_Dir'),
        ),
        migrations.AddField(
            model_name='topic_link',
            name='region',
            field=models.ForeignKey(default=8, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodanews.Region'),
        ),
    ]
