# Generated by Django 2.1.1 on 2018-09-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0076_auto_20180913_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_dir',
            name='region',
            field=models.ForeignKey(default=8, null=True, on_delete=django.db.models.deletion.PROTECT, to='nodanews.Region'),
        ),
    ]
