# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-18 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0078_node_dir_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='STF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('image', models.ImageField(default=b'', upload_to=b'media/nodes')),
                ('update', models.TextField()),
                ('date_updated', models.DateTimeField()),
                ('slug', models.SlugField(default=b' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='STF_Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('banner', models.ImageField(upload_to=b'media/nodes')),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, default=b'')),
                ('slug', models.SlugField(default=b' ', max_length=200)),
                ('node_dir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodanews.Node_Dir')),
            ],
        ),
        migrations.CreateModel(
            name='STF_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default=b'', max_length=300)),
                ('title', models.CharField(blank=True, default=b'', max_length=150)),
                ('STF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.STF')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Media_Org')),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='date_posted',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='stf',
            name='STF_Hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodanews.STF_Hub'),
        ),
        migrations.AddField(
            model_name='stf',
            name='node_dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nodanews.Node_Dir'),
        ),
    ]
