# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-18 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0079_auto_20190618_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='stf',
            name='credit',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='stf_hub',
            name='credit',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
