# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-18 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0081_auto_20190618_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stf',
            old_name='STF_Hub',
            new_name='hub',
        ),
    ]
