# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-18 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0082_auto_20190618_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stf_link',
            old_name='STF',
            new_name='story',
        ),
    ]
