# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-04 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0083_auto_20190618_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaking_link',
            name='posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
