# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-04 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0085_auto_20190904_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stf',
            options={'ordering': ('-date_updated',)},
        ),
    ]
