# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0086_auto_20190904_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stf',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
