# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-03 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodanews', '0087_auto_20190918_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('image', models.ImageField(blank=True, default=b'', upload_to=b'media/temp')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Feature_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default=b'', max_length=300)),
                ('title', models.CharField(blank=True, default=b'', max_length=150)),
                ('posted', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Feature')),
            ],
            options={
                'ordering': ('-posted',),
            },
        ),
        migrations.RemoveField(
            model_name='breaking_link',
            name='region',
        ),
        migrations.AlterField(
            model_name='media_org',
            name='region',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Region'),
        ),
        migrations.AlterField(
            model_name='topic_link',
            name='region',
            field=models.ForeignKey(default=8, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodanews.Region'),
        ),
        migrations.AddField(
            model_name='feature_link',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodanews.Media_Org'),
        ),
    ]
